#!/data/data/com.termux/files/usr/bin/bash
# ============================================================================
# NDK Lite — Project Scaffolding Command
# Copyright (c) 2024-2026 Project Tomorrow Inc.
# Licensed under the Apache License, Version 2.0
# ============================================================================
#
# ndk-lite-new — Creates a new Android native project from templates
#
# Usage:
#   ndk-lite-new <type> <name>
#
# Types:
#   cpp        C++ shared/static library project
#   c          C shared/static library project
#   jni        JNI bridge project (C++ + Java JNI headers)
#   opengl     OpenGL ES project (C++ + GLES2/EGL)
# ============================================================================

set -euo pipefail

NDK_LITE_VERSION="1.0.0"

# --- Colors ------------------------------------------------------------------
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# --- Parse arguments ---------------------------------------------------------
if [[ $# -lt 2 ]]; then
    echo "ndk-lite-new v${NDK_LITE_VERSION} — Project Scaffolding"
    echo ""
    echo "Usage: ndk-lite-new <type> <name>"
    echo ""
    echo "Types:"
    echo "  cpp        C++ library project"
    echo "  c          C library project"
    echo "  jni        JNI bridge project"
    echo "  opengl     OpenGL ES project"
    echo ""
    echo "Examples:"
    echo "  ndk-lite-new cpp mylib"
    echo "  ndk-lite-new jni audio-bridge"
    exit 1
fi

PROJECT_TYPE="$1"
PROJECT_NAME="$2"

# Validate project name
if [[ ! "${PROJECT_NAME}" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    echo -e "${RED}[NDK Lite] Invalid project name: ${PROJECT_NAME}${NC}" >&2
    echo -e "${YELLOW}Must start with a letter and contain only letters, digits, hyphens, underscores${NC}" >&2
    exit 1
fi

# Convert hyphens to underscores for C identifiers
LIB_NAME="${PROJECT_NAME//-/_}"

# --- Create project directory ------------------------------------------------
if [[ -d "${PROJECT_NAME}" ]]; then
    echo -e "${RED}[NDK Lite] Directory already exists: ${PROJECT_NAME}${NC}" >&2
    exit 1
fi

mkdir -p "${PROJECT_NAME}/src"
mkdir -p "${PROJECT_NAME}/include"

# --- Generate project based on type ------------------------------------------
case "${PROJECT_TYPE}" in
    cpp)
        # C++ library project
        cat > "${PROJECT_NAME}/CMakeLists.txt" << CMAKEFILE
# ============================================================================
# ${PROJECT_NAME} — Android ARM64 Native Library
# Generated by NDK Lite v${NDK_LITE_VERSION}
# Copyright (c) $(date +%Y) Project Tomorrow Inc.
# ============================================================================

cmake_minimum_required(VERSION 3.22)

project(${LIB_NAME}
    VERSION 1.0.0
    LANGUAGES CXX
)

# --- Options -----------------------------------------------------------------
option(BUILD_SHARED_LIBS "Build shared library" ON)
option(BUILD_TESTS "Build test programs" OFF)

# --- Source files ------------------------------------------------------------
file(GLOB_RECURSE ${LIB_NAME}_SOURCES
    "src/*.cpp"
    "src/*.cc"
)

file(GLOB_RECURSE ${LIB_NAME}_HEADERS
    "include/*.h"
    "include/*.hpp"
)

# --- Target definition -------------------------------------------------------
if(BUILD_SHARED_LIBS)
    add_library(\${PROJECT_NAME} SHARED \${${LIB_NAME}_SOURCES})
else()
    add_library(\${PROJECT_NAME} STATIC \${${LIB_NAME}_SOURCES})
endif()

# --- Include directories -----------------------------------------------------
target_include_directories(\${PROJECT_NAME}
    PUBLIC
        \${CMAKE_CURRENT_SOURCE_DIR}/include
    PRIVATE
        \${CMAKE_CURRENT_SOURCE_DIR}/src
)

# --- Compile features --------------------------------------------------------
target_compile_features(\${PROJECT_NAME} PUBLIC cxx_std_17)

# --- Link libraries ----------------------------------------------------------
target_link_libraries(\${PROJECT_NAME}
    PRIVATE
        log
)

# --- Export header -----------------------------------------------------------
if(NOT EXISTS "\${CMAKE_CURRENT_SOURCE_DIR}/include/${LIB_NAME}.h")
    file(WRITE "\${CMAKE_CURRENT_SOURCE_DIR}/include/${LIB_NAME}.h"
        "// ${PROJECT_NAME} — Auto-generated by NDK Lite\n"
        "#ifndef ${LIB_NAME^^}_H\n"
        "#define ${LIB_NAME^^}_H\n"
        "\n"
        "#ifdef __cplusplus\n"
        "extern \"C\" {\n"
        "#endif\n"
        "\n"
        "// Your API declarations here\n"
        "void ${LIB_NAME}_init(void);\n"
        "void ${LIB_NAME}_shutdown(void);\n"
        "\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n"
        "\n"
        "#endif /* ${LIB_NAME^^}_H */\n"
    )
endif()
CMAKEFILE

        cat > "${PROJECT_NAME}/src/${LIB_NAME}.cpp" << CPPFILE
// ============================================================================
// ${PROJECT_NAME} — Android ARM64 Native Library
// Generated by NDK Lite v${NDK_LITE_VERSION}
// ============================================================================

#include "${LIB_NAME}.h"
#include <android/log.h>

#define LOG_TAG "${PROJECT_NAME}"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace {

struct ${LIB_NAME}_state {
    bool initialized = false;
};

static ${LIB_NAME}_state g_state;

} // anonymous namespace

extern "C" {

void ${LIB_NAME}_init(void) {
    if (g_state.initialized) {
        LOGI("${PROJECT_NAME} already initialized");
        return;
    }

    LOGI("${PROJECT_NAME} initializing on Android ARM64 [NDK Lite]");
    g_state.initialized = true;
    LOGI("${PROJECT_NAME} initialized successfully");
}

void ${LIB_NAME}_shutdown(void) {
    if (!g_state.initialized) {
        return;
    }

    LOGI("${PROJECT_NAME} shutting down");
    g_state.initialized = false;
}

} // extern "C"
CPPFILE

        cat > "${PROJECT_NAME}/include/${LIB_NAME}.h" << HFILE
// ============================================================================
// ${PROJECT_NAME} — Public API Header
// Generated by NDK Lite v${NDK_LITE_VERSION}
// ============================================================================
#ifndef ${LIB_NAME^^}_H
#define ${LIB_NAME^^}_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Initialize the ${PROJECT_NAME} library.
 * Must be called before any other function.
 */
void ${LIB_NAME}_init(void);

/**
 * Shutdown the ${PROJECT_NAME} library.
 * Call when the library is no longer needed.
 */
void ${LIB_NAME}_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif /* ${LIB_NAME^^}_H */
HFILE
        ;;

    c)
        # C library project
        cat > "${PROJECT_NAME}/CMakeLists.txt" << CMAKEFILE
# ============================================================================
# ${PROJECT_NAME} — Android ARM64 C Library
# Generated by NDK Lite v${NDK_LITE_VERSION}
# ============================================================================

cmake_minimum_required(VERSION 3.22)

project(${LIB_NAME}
    VERSION 1.0.0
    LANGUAGES C
)

option(BUILD_SHARED_LIBS "Build shared library" ON)

file(GLOB_RECURSE ${LIB_NAME}_SOURCES "src/*.c")
file(GLOB_RECURSE ${LIB_NAME}_HEADERS "include/*.h")

if(BUILD_SHARED_LIBS)
    add_library(\${PROJECT_NAME} SHARED \${${LIB_NAME}_SOURCES})
else()
    add_library(\${PROJECT_NAME} STATIC \${${LIB_NAME}_SOURCES})
endif()

target_include_directories(\${PROJECT_NAME}
    PUBLIC \${CMAKE_CURRENT_SOURCE_DIR}/include
    PRIVATE \${CMAKE_CURRENT_SOURCE_DIR}/src
)

target_compile_features(\${PROJECT_NAME} PUBLIC c_std_11)

target_link_libraries(\${PROJECT_NAME} PRIVATE log)
CMAKEFILE

        cat > "${PROJECT_NAME}/src/${LIB_NAME}.c" << CFILE
// ============================================================================
// ${PROJECT_NAME} — Android ARM64 C Library
// Generated by NDK Lite v${NDK_LITE_VERSION}
// ============================================================================

#include "${LIB_NAME}.h"
#include <android/log.h>

#define LOG_TAG "${PROJECT_NAME}"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

static int g_initialized = 0;

void ${LIB_NAME}_init(void) {
    if (g_initialized) return;
    LOGI("${PROJECT_NAME} initializing [NDK Lite]");
    g_initialized = 1;
}

void ${LIB_NAME}_shutdown(void) {
    g_initialized = 0;
}
CFILE

        cat > "${PROJECT_NAME}/include/${LIB_NAME}.h" << HFILE
#ifndef ${LIB_NAME^^}_H
#define ${LIB_NAME^^}_H

#ifdef __cplusplus
extern "C" {
#endif

void ${LIB_NAME}_init(void);
void ${LIB_NAME}_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif
HFILE
        ;;

    jni)
        # JNI bridge project
        mkdir -p "${PROJECT_NAME}/src/jni"
        mkdir -p "${PROJECT_NAME}/include/jni"

        cat > "${PROJECT_NAME}/CMakeLists.txt" << CMAKEFILE
# ============================================================================
# ${PROJECT_NAME} — JNI Bridge Library
# Generated by NDK Lite v${NDK_LITE_VERSION}
# ============================================================================

cmake_minimum_required(VERSION 3.22)

project(${LIB_NAME}
    VERSION 1.0.0
    LANGUAGES CXX
)

add_library(\${PROJECT_NAME} SHARED
    src/jni/${LIB_NAME}_jni.cpp
)

target_include_directories(\${PROJECT_NAME}
    PRIVATE
        \${CMAKE_CURRENT_SOURCE_DIR}/include
        \${CMAKE_CURRENT_SOURCE_DIR}/include/jni
)

target_compile_features(\${PROJECT_NAME} PUBLIC cxx_std_17)

target_link_libraries(\${PROJECT_NAME}
    PRIVATE
        log
        android
)
CMAKEFILE

        cat > "${PROJECT_NAME}/src/jni/${LIB_NAME}_jni.cpp" << JNIFILE
// ============================================================================
// ${PROJECT_NAME} — JNI Bridge Implementation
// Generated by NDK Lite v${NDK_LITE_VERSION}
// ============================================================================

#include <jni.h>
#include <android/log.h>
#include "${LIB_NAME}_jni.h"

#define LOG_TAG "${PROJECT_NAME}-JNI"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

extern "C" {

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    LOGI("${PROJECT_NAME} JNI library loaded [NDK Lite]");
    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL
Java_com_projecttomorrow_${LIB_NAME}_${LIB_NAME}_nativeInit(JNIEnv* env, jobject thiz) {
    LOGI("${PROJECT_NAME} nativeInit called");
    // Initialize native resources here
}

JNIEXPORT void JNICALL
Java_com_projecttomorrow_${LIB_NAME}_${LIB_NAME}_nativeShutdown(JNIEnv* env, jobject thiz) {
    LOGI("${PROJECT_NAME} nativeShutdown called");
    // Release native resources here
}

} // extern "C"
JNIFILE

        cat > "${PROJECT_NAME}/include/jni/${LIB_NAME}_jni.h" << JNIH
#ifndef ${LIB_NAME^^}_JNI_H
#define ${LIB_NAME^^}_JNI_H

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved);

#ifdef __cplusplus
}
#endif

#endif
JNIH
        ;;

    opengl)
        # OpenGL ES project
        mkdir -p "${PROJECT_NAME}/src/gl"
        mkdir -p "${PROJECT_NAME}/include/gl"

        cat > "${PROJECT_NAME}/CMakeLists.txt" << CMAKEFILE
# ============================================================================
# ${PROJECT_NAME} — OpenGL ES Android ARM64 Project
# Generated by NDK Lite v${NDK_LITE_VERSION}
# ============================================================================

cmake_minimum_required(VERSION 3.22)

project(${LIB_NAME}
    VERSION 1.0.0
    LANGUAGES CXX
)

add_library(\${PROJECT_NAME} SHARED
    src/gl/${LIB_NAME}_renderer.cpp
)

target_include_directories(\${PROJECT_NAME}
    PRIVATE
        \${CMAKE_CURRENT_SOURCE_DIR}/include
        \${CMAKE_CURRENT_SOURCE_DIR}/include/gl
)

target_compile_features(\${PROJECT_NAME} PUBLIC cxx_std_17)

target_link_libraries(\${PROJECT_NAME}
    PRIVATE
        log
        android
        EGL
        GLESv2
)
CMAKEFILE

        cat > "${PROJECT_NAME}/src/gl/${LIB_NAME}_renderer.cpp" << GLFILE
// ============================================================================
// ${PROJECT_NAME} — OpenGL ES Renderer
// Generated by NDK Lite v${NDK_LITE_VERSION}
// ============================================================================

#include "${LIB_NAME}_renderer.h"
#include <android/log.h>
#include <EGL/egl.h>
#include <GLES2/gl2.h>

#define LOG_TAG "${PROJECT_NAME}-GL"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,  LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace ${LIB_NAME} {

class Renderer::Impl {
public:
    bool initialize(ANativeWindow* window) {
        display_ = eglGetDisplay(EGL_DEFAULT_DISPLAY);
        if (display_ == EGL_NO_DISPLAY) {
            LOGE("Failed to get EGL display");
            return false;
        }

        EGLint major, minor;
        if (!eglInitialize(display_, &major, &minor)) {
            LOGE("Failed to initialize EGL");
            return false;
        }

        LOGI("EGL initialized: %d.%d [NDK Lite]", major, minor);

        EGLint attribs[] = {
            EGL_RENDER_BUFFER, EGL_BACK_BUFFER,
            EGL_NONE
        };

        EGLConfig config;
        EGLint numConfigs;
        if (!eglChooseConfig(display_, attribs, &config, 1, &numConfigs)) {
            LOGE("Failed to choose EGL config");
            return false;
        }

        EGLint contextAttribs[] = {
            EGL_CONTEXT_CLIENT_VERSION, 2,
            EGL_NONE
        };

        surface_ = eglCreateWindowSurface(display_, config, window, nullptr);
        context_ = eglCreateContext(display_, config, EGL_NO_CONTEXT, contextAttribs);

        if (!eglMakeCurrent(display_, surface_, surface_, context_)) {
            LOGE("Failed to make EGL context current");
            return false;
        }

        LOGI("OpenGL ES context created successfully");
        return true;
    }

    void render() {
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        eglSwapBuffers(display_, surface_);
    }

    void shutdown() {
        if (display_ != EGL_NO_DISPLAY) {
            eglMakeCurrent(display_, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
            if (context_ != EGL_NO_CONTEXT) eglDestroyContext(display_, context_);
            if (surface_ != EGL_NO_SURFACE) eglDestroySurface(display_, surface_);
            eglTerminate(display_);
        }
        display_ = EGL_NO_DISPLAY;
        context_ = EGL_NO_CONTEXT;
        surface_ = EGL_NO_SURFACE;
        LOGI("Renderer shutdown complete");
    }

private:
    EGLDisplay display_ = EGL_NO_DISPLAY;
    EGLSurface surface_ = EGL_NO_SURFACE;
    EGLContext context_ = EGL_NO_CONTEXT;
};

Renderer::Renderer() : impl_(std::make_unique<Impl>()) {}
Renderer::~Renderer() = default;

bool Renderer::initialize(ANativeWindow* window) {
    return impl_->initialize(window);
}

void Renderer::render() {
    impl_->render();
}

void Renderer::shutdown() {
    impl_->shutdown();
}

} // namespace ${LIB_NAME}
GLFILE

        cat > "${PROJECT_NAME}/include/gl/${LIB_NAME}_renderer.h" << GLH
#ifndef ${LIB_NAME^^}_RENDERER_H
#define ${LIB_NAME^^}_RENDERER_H

#include <android/native_window.h>
#include <memory>

namespace ${LIB_NAME} {

class Renderer {
public:
    Renderer();
    ~Renderer();

    bool initialize(ANativeWindow* window);
    void render();
    void shutdown();

private:
    class Impl;
    std::unique_ptr<Impl> impl_;
};

} // namespace ${LIB_NAME}

#endif
GLH
        ;;

    *)
        echo -e "${RED}[NDK Lite] Unknown project type: ${PROJECT_TYPE}${NC}" >&2
        echo -e "${YELLOW}Available types: cpp, c, jni, opengl${NC}" >&2
        rm -rf "${PROJECT_NAME}"
        exit 1
        ;;
esac

# --- Generate common files ---------------------------------------------------

# .gitignore
cat > "${PROJECT_NAME}/.gitignore" << GITIGNORE
# NDK Lite
.ndk-lite-build/
build-output/

# CMake
CMakeCache.txt
CMakeFiles/
cmake_install.cmake

# Compiled
*.o
*.so
*.a
*.dylib
*.dll

# IDE
.vscode/
.idea/
*.swp
*~
GITIGNORE

# ndk-lite.config
cat > "${PROJECT_NAME}/ndk-lite.config" << CONFIG
# NDK Lite Project Configuration
# Generated by ndk-lite-new v${NDK_LITE_VERSION}

[project]
name = ${PROJECT_NAME}
type = ${PROJECT_TYPE}
version = 1.0.0

[build]
api = 26
stl = c++_static
type = shared
generator = ninja
jobs = auto

[output]
dir = build-output
CONFIG

# README
cat > "${PROJECT_NAME}/README.md" << README
# ${PROJECT_NAME}

Android ARM64 native library built with **NDK Lite**.

## Build

\`\`\`bash
ndk-lite-build .
\`\`\`

## Clean Build

\`\`\`bash
ndk-lite-build --clean .
\`\`\`

## Static Library

\`\`\`bash
ndk-lite-build --type=static .
\`\`\`

## Debug Build

\`\`\`bash
ndk-lite-build --debug .
\`\`\`

---
*Generated by NDK Lite v${NDK_LITE_VERSION} — Project Tomorrow Inc.*
README

# --- Summary ----------------------------------------------------------------
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║         Project Created Successfully             ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Name:${NC}       ${PROJECT_NAME}"
echo -e "  ${BOLD}Type:${NC}       ${PROJECT_TYPE}"
echo -e "  ${BOLD}Library:${NC}    lib${LIB_NAME}.so"
echo ""
echo -e "  ${CYAN}Structure:${NC}"
echo -e "    ${PROJECT_NAME}/"
echo -e "    ├── CMakeLists.txt"
echo -e "    ├── ndk-lite.config"
echo -e "    ├── README.md"
echo -e "    ├── .gitignore"
echo -e "    ├── include/"
echo -e "    └── src/"
echo ""
echo -e "  ${BOLD}${YELLOW}Next:${NC} cd ${PROJECT_NAME} && ndk-lite-build ."
echo ""
